##################### Grafana Configuration #####################

[paths]
# Path to where grafana can store temp files, sessions, and the sqlite3 db
data = /var/lib/grafana

# Directory where grafana can store logs
logs = /var/log/grafana

# Directory where grafana will automatically scan and look for plugins
plugins = /var/lib/grafana/plugins

# Folder that contains provisioning config files
provisioning = conf/provisioning

#################################### Server ####################################
[server]
# Protocol (http, https, h2, socket)
protocol = http

# The http port to use
http_port = 3000

# The public facing domain name used to access grafana from a browser
domain = localhost

#################################### Database ####################################
[database]
# Either "mysql", "postgres" or "sqlite3"
type = sqlite3

# For "sqlite3" only, path relative to data_path setting
path = grafana.db

#################################### Security ####################################
[security]
# Default admin user, created on startup
admin_user = admin

# Default admin password, can be changed before first start of grafana
admin_password = admin

# Used for signing
secret_key = SW2YcwTIb9zpOOhoPsMm

# Set to true if you want to allow browsers to render Grafana in a <frame>, <iframe>, <embed> or <object>
allow_embedding = true

#################################### Users ###############################
[users]
# Disable user signup / registration
allow_sign_up = false

# Allow non admin users to create organizations
allow_org_create = false

# Set to true to automatically assign new users to the default organization (id 1)
auto_assign_org = true

# Default role new users will be automatically assigned
auto_assign_org_role = Viewer

# Default UI theme ("dark" or "light")
default_theme = dark

# Viewers can edit/inspect dashboard settings in the browser. But not save the dashboard.
viewers_can_edit = false

#################################### Auth ####################################
[auth]
# Set to true to disable (hide) the login form, useful if you use OAuth
disable_login_form = false

# Set to true to disable the signout link in the side menu
disable_signout_menu = false

#################################### Anonymous Auth ######################
[auth.anonymous]
# Enable anonymous access
enabled = true

# Specify organization name that should be used for unauthenticated users
org_name = Main Org.

# Specify role for unauthenticated users
org_role = Admin

#################################### Basic Auth ##########################
[auth.basic]
enabled = true

#################################### Logging ##########################
[log]
# Either "console", "file", "syslog". Default is console and file
mode = console file

# Either "debug", "info", "warn", "error", "critical"
level = info

# For "console" mode only
[log.console]
# Log line format, valid options are text, console and json
format = console

# For "file" mode only
[log.file]
# Log line format, valid options are text, console and json
format = text

# This enables automated log rotate
log_rotate = true

# Max line number of single file
max_lines = 1000000

# Max size shift of single file (256MB)
max_size_shift = 28

# Segment log daily
daily_rotate = true

# Expired days of log file (delete after max days)
max_days = 7

#################################### Unified Alerting ############################
[unified_alerting]
# Enable unified alerting (default in Grafana 9+)
enabled = true

# Makes it possible to turn off alert rule execution but alerting UI is visible
execute_alerts = true

#################################### Explore #############################
[explore]
# Enable the Explore section
enabled = true

#################################### Metrics ##########################
[metrics]
# Disable / Enable internal metrics
enabled = true

# Disable total stats (stat_totals_*) metrics to be generated
disable_total_stats = false

#################################### Grafana.com integration ##########################
[grafana_com]
url = https://grafana.com

#################################### Panels ############################
[panels]
# If set to true Grafana will allow script tags in text panels
disable_sanitize_html = false

#################################### Plugins ############################
[plugins]
enable_alpha = false
