{
 "title": "cAdvisor Docker Insights",
 "description": "This Grafana dashboard offers a basic overview of key performance metrics for Docker containers in your system.",
 "tags": [
  "docker",
  "cadvisor",
  "containers"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(container_last_seen{name=~\".+\"}, server)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{name=~\".+\",server=~\"$server\"})",
     "legendFormat": "Running Containers"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\",server=~\"$server\"}[10m])) by (name, server) * 100",
     "legendFormat": "{{name}} ({{server}})"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{name=~\".+\",server=~\"$server\"}[10m])) by (name, server)",
     "legendFormat": "{{name}} ({{server}})"
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_cache{name=~\".+\",server=~\"$server\"}[10m])) by (name, server)",
     "legendFormat": "{{name}} ({{server}})"
    }
   ]
  },
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Reads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=~\".+\",server=~\"$server\"}[10m])) by (name, server)",
     "legendFormat": "{{name}} ({{server}})"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=~\".+\",server=~\"$server\"}[10m])) by (name, server)",
     "legendFormat": "{{name}} ({{server}})"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\",server=~\"$server\"}[10m])) by (name, server)",
     "legendFormat": "{{name}} ({{server}})"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\",server=~\"$server\"}[10m])) by (name, server)",
     "legendFormat": "{{name}} ({{server}})"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Container Restarts",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "count by(name, server) (count_over_time(container_last_seen{name=~\".+\",server=~\"$server\"}[$__range]))",
     "legendFormat": "{{name}} ({{server}})"
    }
   ]
  }
 ]
}