{
 "title": "Server Metrics",
 "tags": [
  "prometheus",
  "node-exporter",
  "server-monitoring"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasourceProm", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Monitored Servers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"node-exporter\"} == 1)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (server) (\n  label_replace(time() - node_boot_time_seconds, \"uptime\", \"$1\", \"instance\", \"(.*)\")\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(server) (rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (\n  (\n    (avg by(server) (node_memory_MemAvailable_bytes{job=\"node-exporter\"}) or \n    (avg by(server) (node_memory_MemFree_bytes{job=\"node-exporter\"}) + \n    avg by(server) (node_memory_Cached_bytes{job=\"node-exporter\"}) + \n    avg by(server) (node_memory_Buffers_bytes{job=\"node-exporter\"})))\n  ) / avg by(server) (node_memory_MemTotal_bytes{job=\"node-exporter\"})\n))\n",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "avg by(server) (node_load5{job=\"node-exporter\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (node_filesystem_size_bytes{job=\"node-exporter\", mountpoint=\"/\"} - node_filesystem_free_bytes{job=\"node-exporter\", mountpoint=\"/\"}) / node_filesystem_size_bytes{job=\"node-exporter\", mountpoint=\"/\"}\n\n",
     "legendFormat": "{{server}}"
    }
   ]
  }
 ]
}